Test test workflow (#11)
feat: add test job to github workflow

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -6,17 +6,63 @@ on:
       - main
       - prod
       - feat-*
+      - test-*
     paths: 
       - 'services/**'
       - '.github/**'
   workflow_dispatch:
 
 jobs:
+  test:
+    name: Run Tests
+    timeout-minutes: 5
+    runs-on: ubuntu-latest
+    defaults:
+      run:
+        working-directory: services/server
+    steps:
+      - uses: actions/checkout@v4
+        with:
+          sparse-checkout: |
+            .github
+            services
+
+      - name: Check Required variables and secrets
+        run: |
+          if [[ -z "${{ secrets.TEST_FIREBASE_API_KEY }}" ]]; then
+            echo "TEST_FIREBASE_API_KEY secret is missing";
+            exit 1;
+          fi
+          if [[ -z "${{ secrets.TEST_FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}" ]]; then
+            echo "TEST_FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 secret is missing";
+            exit 1;
+          fi
+
+      - name: Set up Go
+        uses: actions/setup-go@v5
+        with:
+          go-version: '1.22.2'
+
+      - name: Install dependencies
+        run: go mod download
+
+      - name: Create firebase-service-account.json file
+        run: |
+          mkdir -p ./secrets
+          echo "${{ secrets.TEST_FIREBASE_SERVICE_ACCOUNT_KEY_BASE64 }}" | base64 -d > ./secrets/firebase_service_account_key.json
+          ls -la ./secrets
+
+      - name: Run tests
+        run: |
+          ls -la ./secrets
+          TEST_FIREBASE_API_KEY=${{ secrets.TEST_FIREBASE_API_KEY }} make test
+
   ci:
     name: Build and Push Docker Image, Deploy to Linode K8s
     env:
       API_VERSION: v1
     timeout-minutes: 5
+    needs: test
     defaults:
       run:
         working-directory: services/server
@@ -43,11 +89,11 @@ jobs:
             exit 1;
           fi
           if [[ -z "${{ secrets.POSTGRES_HOST }}" ]]; then
-            echo "LINODE_KUBECONFIG secret is missing";
+            echo "POSTGRES_HOST secret is missing";
             exit 1;
           fi
           if [[ -z "${{ secrets.POSTGRES_PASSWORD }}" ]]; then
-            echo "LINODE_KUBECONFIG secret is missing";
+            echo "POSTGRES_PASSWORD secret is missing";
             exit 1;
           fi
 
